-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL,
    email "char",
    password "char" NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT "UK_Users_email" UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.employers
(
    company_id integer NOT NULL,
    company_name "char"[] NOT NULL,
    phone_number "char"[] NOT NULL,
    PRIMARY KEY (company_id)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    employee_id integer NOT NULL,
    first_name "char"[] NOT NULL,
    last_name "char"[] NOT NULL,
    national_identity "char"[] NOT NULL,
    PRIMARY KEY (employee_id),
    CONSTRAINT "UK_Employees_NationalNumber" UNIQUE (national_identity)
);

CREATE TABLE IF NOT EXISTS public.personnels
(
    personnel_id integer NOT NULL,
    PRIMARY KEY (personnel_id)
);

CREATE TABLE IF NOT EXISTS public.email_verifications
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    create_at date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mernis_verifications
(
    id integer NOT NULL,
    employee_id integer NOT NULL,
    created_at date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.personnel_verifications
(
    id integer NOT NULL,
    company_id integer NOT NULL,
    personnel_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.job_positions
(
    id integer,
    personnel_id integer NOT NULL,
    position_name "char"[] NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT "Uniuqe" UNIQUE (position_name)
);

ALTER TABLE IF EXISTS public.employers
    ADD FOREIGN KEY (company_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.personnels
    ADD FOREIGN KEY (personnel_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.email_verifications
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.mernis_verifications
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.personnel_verifications
    ADD CONSTRAINT "FG_Employers" FOREIGN KEY (company_id)
    REFERENCES public.employers (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.personnel_verifications
    ADD FOREIGN KEY (personnel_id)
    REFERENCES public.personnels (personnel_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.job_positions
    ADD FOREIGN KEY (personnel_id)
    REFERENCES public.personnels (personnel_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;